package com.devomind.gallerysearch

import com.devomind.gallerysearch.db.EmbeddingSourceEntity
import com.devomind.gallerysearch.db.FaceEntity
import com.devomind.gallerysearch.db.MediaMetadataEntity
import com.devomind.gallerysearch.db.RoomBatching
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.lang.reflect.Modifier

/**
 * SQLite's ceiling on bound variables — 999 on every build this app's minSdk reaches — is a wall a
 * statement either fits or fails to compile, and it only shows up on the phone, on whichever pass is
 * first to carry enough photos. Room hides the wall because an `IN (:uris)` binds one variable per
 * uri while a bulk `@Insert` binds one per *column*, so the "chunk at 900" that rescues a uri list is
 * 11,700 variables for `media_metadata` rows.
 *
 * These tests hold the two halves together: the arithmetic, and the row widths the arithmetic is told.
 */
class RoomBatchingTest {

    private val sqliteVariableLimit = 999

    @Test
    fun everyBulkInsertStaysUnderTheVariableCeiling() {
        val rows = listOf(
            "media_metadata" to MediaMetadataEntity.BindVariables,
            "embedding_source" to EmbeddingSourceEntity.BindVariables,
            "faces" to FaceEntity.BindVariables
        )
        for ((table, variablesPerRow) in rows) {
            val bound = RoomBatching.chunkSizeFor(variablesPerRow) * variablesPerRow
            assertTrue("$table would bind $bound variables in one statement", bound <= sqliteVariableLimit)
        }
    }

    @Test
    fun anInListGetsTheWholeCeilingAndARowListGetsItsShare() {
        assertEquals(900, RoomBatching.chunkSizeFor(1))
        assertEquals(69, RoomBatching.chunkSizeFor(13))
        // A row wider than the ceiling still writes one element at a time instead of empty chunks.
        assertEquals(1, RoomBatching.chunkSizeFor(5000))
        // A width of nothing is read as a width of one, never as an unbounded chunk.
        assertEquals(900, RoomBatching.chunkSizeFor(0))
    }

    @Test
    fun chunksCoverEveryElementOnceInOrder() {
        assertEquals(emptyList<List<Int>>(), RoomBatching.chunks(emptyList<Int>()))
        for (size in listOf(1, 899, 900, 901, 5000)) {
            val items = (1..size).toList()
            val chunks = RoomBatching.chunks(items)
            assertEquals("a list of $size lost or duplicated elements", items, chunks.flatten())
            assertTrue(
                "a chunk of ${chunks.maxOf { it.size }} binds past the ceiling",
                chunks.all { it.size <= RoomBatching.chunkSizeFor(1) }
            )
        }
        assertEquals(3, RoomBatching.chunks((1..200).toList(), MediaMetadataEntity.BindVariables).size)
    }

    /**
     * The [com.devomind.gallerysearch.db.MediaMetadataEntity.BindVariables] constants are only honest
     * while they match their entity. Room's columns are a data class's own stored properties, so the
     * count is read off the class and an added column fails here instead of on a device.
     */
    @Test
    fun theDeclaredBindCountsMatchTheEntities() {
        assertEquals(MediaMetadataEntity.BindVariables, columnsOf(MediaMetadataEntity::class.java))
        assertEquals(EmbeddingSourceEntity.BindVariables, columnsOf(EmbeddingSourceEntity::class.java))
        // faces' id is autogenerated, so Room leaves it out of the INSERT and it binds nothing.
        assertEquals(FaceEntity.BindVariables, columnsOf(FaceEntity::class.java) - 1)
    }

    private fun columnsOf(entity: Class<*>): Int =
        entity.declaredFields.count { !Modifier.isStatic(it.modifiers) && !it.isSynthetic }
}
